### ISSUE TITLE
Clean UP & Dockerization eos2a9n

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos2a9n#1]

**Comment by GemmaTuron** [comment]
Hi @samuelmaina 
I have updated the workflows for this model

**Comment by samuelmaina** [comment]
Okay, @GemmaTuron

**Comment by GemmaTuron** [comment]
@samuelmaina 

The PR is failing, please revise it. Also, could you add the urllib function to convert the smiles into url format?
```
Lines = [
    "[Ca++].NC1=NC(=O)C2=C(NCC(CNc3ccc(cc3)C(=O)N[C@@H](CCC([O-])=O)C([O-])=O)N2C=O)N1"
]

fp     = 'ECfp4'
db     = 'GDBChEMBL'
nnc    = '100'

data = []
for input_smiles in Lines:
    input_smiles = input_smiles.strip() 
    url_encoded_smiles = urllib.parse.quote(input_smiles)

    url = 'https://gdb-chembl-simsearch.gdb.tools/search?smi=' + url_encoded_smiles +  '&fp=' + fp + '&db=' + db + '&nnc=' + nnc
    print(url)
    #r = requests.get(url)
```

**Comment by samuelmaina** [comment]
Hello @GemmaTuron ,
I am getting only getting the results for the first 4 either when I use the run.sh or with ersilia. I have tried to sleep for some seconds before making the next request but the results always show for the first 4 . I have tried  shuffle the smiles but only the first 4 have the 100 smiles.
The other have this `Server full. Please try again later` page. Any workaround this?
```
<!-- DEFAULT HEADER INDEPENDENT OF RESULT -->
<html>
<head>
<link href="main.css" rel="STYLESHEET" type="text/css"/>
<title>Search results of CCCSc1ccc2nc(NC(=O)OC)[nH]c2c1 in ChEMBL</title>
<link href="css/table3.css" rel="STYLESHEET" type="text/css"/>
<link href="css/gButtons1.css" rel="STYLESHEET" type="text/css"/>
</head>
<body>
<h2>Error!</h2>Server full. Please try again later!<br/><br/><input onclick="history.go(-1)" type="button" value="Go Back"/><br/></body></html>

```
[output (2).csv](https://github.com/ersilia-os/eos2a9n/files/12248509/output.2.csv)
[input.csv](https://github.com/ersilia-os/eos2a9n/files/12248511/input.csv)a
[eos2a9n_cli_fetch.log](https://github.com/ersilia-os/eos2a9n/files/12248531/eos2a9n_cli_fetch.log)
[eos2a9n_cli_eml_pred.csv](https://github.com/ersilia-os/eos2a9n/files/12248534/eos2a9n_cli_eml_pred.csv)

**Comment by GemmaTuron** [comment]
indeed the website seems down, @miquelduranfrigola you mentioned something about the IP for this service, did you update it?

**Comment by GemmaTuron** [comment]
@samuelmaina 

I do not encounter the limit. Can you please open a PR with the refactored code, including the bit to convert smiles to URL format (it should pass the PR tests in any case since it is only calculating a few molecules at fetch time) and we will take it from there?
the same for https://github.com/ersilia-os/eos54c7/issues/1

**Comment by samuelmaina** [comment]
Hi @GemmaTuron ,
I have made a PR, the tests are being run

**Comment by GemmaTuron** [comment]
Hello @samuelmaina 

I have worked a bit on this model:
- Added a time sleep of 10 s between queries, which is sufficient to get most molecules
- Added a check to re run molecules we did not get in the first round, just in case
- Improved the header of the output

I'll close this model as completed.
